# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wall_seg/WallInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class WallInfo(genpy.Message):
  _md5sum = "94095140c7fde5508eeca8261235bdf7"
  _type = "wall_seg/WallInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
uint8 wall_id
geometry_msgs/Point corner_position
float64 angle
geometry_msgs/Point centroid
geometry_msgs/Vector3 normal
geometry_msgs/Point min
geometry_msgs/Point max
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','wall_id','corner_position','angle','centroid','normal','min','max']
  _slot_types = ['std_msgs/Header','uint8','geometry_msgs/Point','float64','geometry_msgs/Point','geometry_msgs/Vector3','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,wall_id,corner_position,angle,centroid,normal,min,max

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WallInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.wall_id is None:
        self.wall_id = 0
      if self.corner_position is None:
        self.corner_position = geometry_msgs.msg.Point()
      if self.angle is None:
        self.angle = 0.
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
    else:
      self.header = std_msgs.msg.Header()
      self.wall_id = 0
      self.corner_position = geometry_msgs.msg.Point()
      self.angle = 0.
      self.centroid = geometry_msgs.msg.Point()
      self.normal = geometry_msgs.msg.Vector3()
      self.min = geometry_msgs.msg.Point()
      self.max = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B16d().pack(_x.wall_id, _x.corner_position.x, _x.corner_position.y, _x.corner_position.z, _x.angle, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.corner_position is None:
        self.corner_position = geometry_msgs.msg.Point()
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.wall_id, _x.corner_position.x, _x.corner_position.y, _x.corner_position.z, _x.angle, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z,) = _get_struct_B16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B16d().pack(_x.wall_id, _x.corner_position.x, _x.corner_position.y, _x.corner_position.z, _x.angle, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.corner_position is None:
        self.corner_position = geometry_msgs.msg.Point()
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 129
      (_x.wall_id, _x.corner_position.x, _x.corner_position.y, _x.corner_position.z, _x.angle, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z,) = _get_struct_B16d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B16d = None
def _get_struct_B16d():
    global _struct_B16d
    if _struct_B16d is None:
        _struct_B16d = struct.Struct("<B16d")
    return _struct_B16d
